apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-llm-server
  labels:
    app: mock-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-llm
  template:
    metadata:
      labels:
        app: mock-llm
    spec:
      containers:
      - name: server
        image: gcr.io/$PROJECT_ID/mock-llm-server:latest
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
