apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app-deployment
  labels:
    app: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app-container
        image: us-central1-docker.pkg.dev/$PROJECTID/rag-poc/rag-app:latest
        ports:
        - containerPort: 7860
        env:
        - name: LLM_SERVICE_HOST
          value: "http://mock-llm-service"
        - name: LLM_SERVICE_PORT
          value: "8001"
        resources:
          requests:
            cpu: "250m"   # 최소한 이 정도 요청(request)이 있어야 함
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      #   volumeMounts:
      #   - name: uploads-volume
      #     mountPath: "/app/uploads"
      # volumes:
      # - name: uploads-volume
      #   emptyDir: {}
