apiVersion: v1
kind: Service
metadata:
  name: rag-app-service
  labels:
    app: rag-app
spec:
  type: LoadBalancer
  selector:
    app: rag-app
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
    name: http
