version: '3.8'

services:
  # --- Etcd ---
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    # container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"

  # --- MinIO ---
  minio:
    image: minio/minio:latest
    # container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  # --- Milvus Standalone ---
  milvus:
    image: milvusdb/milvus:v2.2.14
    # container_name: milvus
    depends_on:
      - etcd
      - minio
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - DATA_PATH=/var/lib/milvus/data
      - WAL_PATH=/var/lib/milvus/wal
      - LOG_PATH=/var/lib/milvus/logs
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./milvus_data:/var/lib/milvus
    platform: linux/amd64

  # --- Zookeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    # container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # --- Kafka ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    # container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  minio_data:
  milvus_data:
